// src/components/Button/Button.tsx
import type {
  ButtonHTMLAttributes,
  PropsWithChildren,
} from 'react';
import {
  buttonStyles,
  type ButtonStylesProps,
} from './Button.css.ts';

export namespace Button {
  export type Props = PropsWithChildren<
    & ButtonStylesProps
    & ButtonHTMLAttributes<HTMLButtonElement>
    & {}
  >;
}

function Button({
  children,
  className,
  variant,
  ...props
}: Button.Props) {
  return (
    <button
      {...props}
      className={[buttonStyles({ variant }), className].filter(Boolean).join(' ')}
    >
      {children}
    </button>
  );
}

export default Button;

// src/components/Button/Button.vue
<template>
  <button :class="{ [buttonStyles({ variant })]: true }">
    <slot />
  </button>
</template>

<script setup lang='ts'>
import { buttonStyles, type ButtonStylesProps } from './Button.css.ts';
interface Props {
  // Ugly hack for Vue T_T (generics unsupported in props determination)
  variant: (ButtonStylesProps & {})["variant"]
}
const { variant } = defineProps<Props>();
</script>
